swagger: '2.0'
info:
  x-ibm-name: transcribe-voice-recording
  title: transcribe-voice-recording
  version: 1.0.0
schemes:
  - https
host: $(catalog.host)
basePath: /transcribe-voice-recording
consumes:
  - application/json
produces:
  - application/json
securityDefinitions: {}
security: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          target-url: 'https://openwhisk.ng.bluemix.net/api/v1/web/amalamine_banking-buddy-guide/default/transcribe-voice-recording?blocking=true'
          username: '866821aa-24e4-4578-9cae-6fd13e57b17c'
          password: '7lbqaCdlYEUDLg68poEvyClYIOp2IwfzvY0UcxxtZKZOAuJ1QTIIOvLqcobfeJdQ'
          verb: POST
  phase: realized
paths:
  /transcribe-voice-recording:
    get:
      responses:
        '200':
          description: 200 OK
    post:
      responses:
        '200':
          description: 200 OK
definitions: {}
tags: []
